[package]
name = "mlatu"
version = "0.1.0"
edition = "2021"
description = "The mlatu programming language"
repository = "https://github.com/mlatu-lang/mlatu"
readme = "docs/README.md"
keywords = ["cli", "parser", "langdev", "language"]
categories = ["command-line-utilities", "compilers", "text-editors"]
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
combine = "4.6.1"
unic-ucd = "0.9.0"

[features]
