name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable
      - name: Build
        run: nimble build -Y
      - name: Release
        uses: softprops/action-gh-release@v1
        if: "contains(github.event.head_commit.message, '[release]')"
        with:
          files: ./mlatu