name: 'workflow'

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        npm install --global esy 
        esy install
        esy build 
        cp -f $(esy echo "{self.target_dir / 'default' / 'bin' / 'main.exe'}") ./mlatu

    - uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        files: |
          mlatu
          LICENSE.md
